# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99a4b7e4826ee870b56f69cb2c353c4b89c45ab2f73a03d6b030f47e490862377f979b6ff394bafcd07027b9144bec0b8a1352b23f31b8f28e8a39cfe4df3eb5

test:
  secret_key_base: 0a446650b81d7ab7bc6c913223ca6e7bd4c0bca347e5ee8527490fab26fbad2398b04ff0322c3f4ad31db035976023807965e9a15cdf2e0b85749ffa0612c169

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["PROD_SECRET_KEY_BASE"] %>
